### PR TITLE
A screenshot of branch protection is added to the readme branch

### PR DESCRIPTION
**Pull request by Ronin1702**
- A screenshot of branch protection is added to the readme branch.
- Edited the readme to include some credits.

### CODE REVIEW

**Comment by CQlove** [comment]
it's working

**Comment by CQlove** [comment]
first try

**Review by CQlove — CHANGES_REQUESTED** [review]
I am not sure if we should use <li> tag in Readme

**Review by CQlove — APPROVED** [review]
the tag is working,nvm

**Comment by Ronin1702** [comment]
- This the first try for collaborative functions in Github.
- I'm merging a pull request approved by @CQlove

**Pull request merged**
